### ISSUE TITLE
Script Issue!

### ISSUE THREAD

**Issue by MatinDark** [MisterChocker/esx_pursuit_helper#1]
Hello thanks for your cool script and thanks for sharing it for free, but there is a problem when I Press M button nothing happens, and there is no error on console either!

**Comment by MisterChocker** [comment]
hello, if my script still works on the current version of FiveMP you should be able to activate/deploy the gps tracker to a vehicle by following it. More or less you have to position your vehicle behind another vehicle.

Take a look at my demos: https://www.twitch.tv/videos/358915107 or https://www.twitch.tv/videos/358917106

**Comment by MatinDark** [comment]
thanks problem solved <3

**Comment by MatinDark** [comment]
And there is something else, it's a bit unrealistic it keeps tracking vehicles when they are more than 1 miles away from you, is that possible to force the script to close GPS connection when the vehicle is more than 0.25 miles away from you or do something when the officer step out of vehicle tracking process stop?

**Comment by MisterChocker** [comment]
I understand your concern.
This system is desired to be realistic.
GPS Tracker from police are sending their location via an secured web connection to the police.
Keep in mind that this script only tracks the vehicle it self, not the occupants.
You can simply pull over and leave the vehicle behind or what so ever.
This tool is designed to make the streets safer and can only fulfill its job by not forcing the police to chase after that vehicle but wich a bit of a distance.

There might be a couple of ways to nerf this feature.
This system is also special because it does not allow the tracked vehicle to despawn as GTA normally does when no player is nearby.

So i am sorry to tell that this script will not have a distance limit to it.
However it is not designed to chase a player that´s in it.
It is designed to ensure public safety by aborting the pursuit and visiting the vehicle afterwards.

I hope you can understand my point of view.

However you can, as we did, create rules when your cops can use this feature.
Once a GPS tracker is deployed it will share its Location to the police computer and any other unity as well.

**Comment by MisterChocker** [comment]
Would you mind to tell me what you did to make it work?

**Comment by MatinDark** [comment]
About solving issue it was my own mistake, I thought I should put GPS on the vehicle, so I was pressing M when I was on foot, and I realized I should press M while I am on the vehicle that's how it solved, and about distance limit do you have any suggestion how to create one for this script, some tips or something like that?!

**Comment by MisterChocker** [comment]
Ah okay, nice to hear it still works.
Well i guess you gotta get both positions, yours and the others, and then kinda measure the distance between.
But keep in mind that this script is not designed for that purpose..
Cause data does not get sent to you or your vehicle but to the police computer and from there to all police units.
And honestly do not know why it should have a distance limit.. its not the gps that transmits anything its the internet connection from the tracker that sends data..  most people get the actual "Science" wrong.

Anyway have fun with it and enjoy it´s features.

**Comment by brescoudos** [comment]
merci du partage super travail
